class CfgPatches
{
	class LT_Vehicles
	{
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"LiontoothGroup_Base",
			"A3_Soft_F_Orange",
			"rhs_c_t72",
			"rhsusf_c_ch53"
		};
		units[]=
		{
			"V_O_LT_UAZ",
			"V_O_LT_UAZ_DSHKM",
			"V_O_LT_M1025",
			"V_O_LT_M1025_M2",
			"V_O_LT_Van",
			"V_O_LT_Van_Cargo",
			"V_O_LT_M113",
			"V_O_LT_BTR80",
			"V_O_LT_T72",
			"V_O_LT_Railgun_Tank",
			"V_I_LT_UAZ",
			"V_I_LT_UAZ_DSHKM",
			"V_I_LT_M1025",
			"V_I_LT_M1025_M2",
			"V_I_LT_Van",
			"V_I_LT_Van_Cargo",
			"V_I_LT_M113",
			"V_I_LT_BTR80",
			"V_I_LT_T72",
			"V_I_LT_Railgun_Tank",
			"V_O_LT_MH6",
			"V_O_LT_AH6",
			"V_O_LT_CH53E",
			"V_O_LT_UH1H",
			"V_O_LT_MI24",
			"V_O_LT_Gripen",
			"V_O_LT_L159",
			"V_O_LT_VTOL",
			"V_O_LT_C130J",
			"V_I_LT_MH6",
			"V_I_LT_AH6",
			"V_I_LT_CH53E",
			"V_I_LT_UH1H",
			"V_I_LT_MI24",
			"V_I_LT_Gripen",
			"V_I_LT_L159",
			"V_I_LT_VTOL",
			"V_I_LT_C130J",
			"T_O_LT_M2",
			"T_O_LT_M2_High",
			"T_O_LT_AGS30",
			"T_O_LT_ZU23",
			"T_O_LT_Mortar",
			"T_I_LT_M2",
			"T_I_LT_M2_High",
			"T_I_LT_AGS30",
			"T_I_LT_ZU23",
			"T_I_LT_Mortar"
		};
	};
};