class CfgPatches
{
	class LT_Vehicles
	{
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"LiontoothGroup_Base"
		};
		units[]=
		{
			"V_LT_UAZ",
			"V_LT_UAZ_DSHKM",
			"V_LT_M1025",
			"V_LT_M1025_M2",
			"V_LT_Van",
			"V_LT_Van_Cargo",
			"V_LT_BTR80",
			"V_LT_T72",
			"V_LT_Railgun_Tank",
			"V_LT_MH6",
			"V_LT_AH6",
			"V_LT_Gripen",
			"V_LT_L159",
			"V_LT_C130J",
			"V_LT_UH1H",
			"V_LT_MI24",
			"V_LT_CH53E",
			"V_LT_VTOL",
			"T_LT_M2",
			"T_LT_M2_High",
			"T_LT_AGS30",
			"T_LT_ZU23",
			"T_LT_Mortar"
		};
	};
};