class CfgPatches{
	class LT_Units {
		weapons[] = {};
		requiredVersion=0.1;
		requiredAddons[] = {
			"LiontoothGroup_Base"
		};
		units[] = {
			"O_LT_Rifleman",
			"O_LT_Rifleman_GL",
			"O_LT_Officer",
			"O_LT_Scout",
			"O_LT_Autorifleman",
			"O_LT_GPMG",
			"O_LT_AT",
			"O_LT_AA",
			"O_LT_Medic",
			"O_LT_Engineer",
			"O_LT_Marksman",
			"O_LT_Sniper",
			"O_LT_Crewman",
			"O_LT_Pilot",
			"O_LT_HeliPilot",
			"I_LT_Rifleman",
			"I_LT_Rifleman_GL",
			"I_LT_Officer",
			"I_LT_Scout",
			"I_LT_Autorifleman",
			"I_LT_GPMG",
			"I_LT_AT",
			"I_LT_AA",
			"I_LT_Medic",
			"I_LT_Engineer",
			"I_LT_Marksman",
			"I_LT_Sniper",
			"I_LT_Crewman",
			"I_LT_Pilot",
			"I_LT_HeliPilot",
			"O_LT_Rifleman_D",
			"O_LT_Rifleman_GL_D",
			"O_LT_Officer_D",
			"O_LT_Scout_D",
			"O_LT_Autorifleman_D",
			"O_LT_GPMG_D",
			"O_LT_AT_D",
			"O_LT_AA_D",
			"O_LT_Medic_D",
			"O_LT_Engineer_D",
			"O_LT_Marksman_D",
			"I_LT_Rifleman_D",
			"I_LT_Rifleman_GL_D",
			"I_LT_Officer_D",
			"I_LT_Scout_D",
			"I_LT_Autorifleman_D",
			"I_LT_GPMG_D",
			"I_LT_AT_D",
			"I_LT_AA_D",
			"I_LT_Medic_D",
			"I_LT_Engineer_D",
			"I_LT_Marksman_D"
		};
	};
};