#include "CfgPatches.hpp"

class CfgVehicles
{
	class I_LT_Base;
	class I_LT_Infantry_Base;
	class I_LT_Rifleman: I_LT_Infantry_Base
	{
		displayName="Rifleman";
		scope=2;
		scopeCurator=2;
	};
	class I_LT_Officer: I_LT_Infantry_Base
	{
		displayName="Officer";
		scope=2;
		scopeCurator=2;
		weapons[] = {
			"SMG_05_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[] = {
			"SMG_05_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[] = {
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		respawnMagazines[] = {
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_H_SLA_BeretRed",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_H_SLA_BeretRed",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Scout: I_LT_Infantry_Base
	{
		displayName="Scout";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_P90_Reflex",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_P90_Reflex",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"ACE_M84",
			"ACE_M84",
			"ACE_M84"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"ACE_M84",
			"ACE_M84",
			"ACE_M84"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_H_PMC_Cap_Back_EP_Grey",
			"G_Shades_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_H_PMC_Cap_Back_EP_Grey",
			"G_Shades_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Rifleman_GL: I_LT_Infantry_Base
	{
		displayName="Grenadier";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_VHSD2_GL",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_VHSD2_GL",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		respawnMagazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Grenadier",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Grenadier",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Autorifleman: I_LT_Infantry_Base
	{
		displayName="Autorifleman";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Carryall_Auto";
		weapons[]=
		{
			"W_LT_RPK74",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_RPK74",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_45Rnd_545X39_7N22_AK",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		respawnMagazines[]=
		{
			"rhs_45Rnd_545X39_7N22_AK",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Empty",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Empty",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_GPMG: I_LT_Autorifleman
	{
		displayName="Machinegunner";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Carryall_GPMG";
		weapons[]=
		{
			"rhs_weap_pkp",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pkp",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_100Rnd_762x54mmR_green",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"rhs_100Rnd_762x54mmR_green",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class I_LT_AT: I_LT_Infantry_Base
	{
		displayName="Anti-Tank Specialist";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		backpack="B_LT_Carryall_AT";
		weapons[]=
		{
			"W_LT_VHSD2_Holo",
			"rhs_weap_rpg7",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_VHSD2_Holo",
			"rhs_weap_rpg7",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"rhs_rpg7_TBG7V_mag"
		};
		respawnMagazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"rhs_rpg7_TBG7V_mag"
		};
	};
	class I_LT_AA: I_LT_Infantry_Base
	{
		displayName="Anti-Air Specialist";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		weapons[]=
		{
			"W_LT_VHSD2_Holo",
			"rhs_weap_fim92",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_VHSD2_Holo",
			"rhs_weap_fim92",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"rhs_fim92_mag"
		};
		respawnMagazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"rhs_fim92_mag"
		};
	};
	class I_LT_Medic: I_LT_Infantry_Base
	{
		displayName="Medic";
		scope=2;
		scopeCurator=2;
		icon="iconManMedic";
		attendant=1;
		backpack="B_LT_MedicalPack";
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_morphine"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_morphine"
		};
		linkedItems[]=
		{
			"V_TacVestIR_blk",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVestIR_blk",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Engineer: I_LT_Infantry_Base
	{
		displayName="Engineer";
		scope=2;
		scopeCurator=2;
		icon="iconManEngineer";
		engineer=1;
		canDeactivateMines=1;
		weapons[]=
		{
			"rhs_weap_M590_8RD",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_M590_8RD",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_8Rnd_Slug",
			"rhsusf_8Rnd_Slug",
			"rhsusf_8Rnd_Slug",
			"rhsusf_8Rnd_00Buck",
			"rhsusf_8Rnd_00Buck",
			"rhsusf_8Rnd_00Buck",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"ACE_M84",
			"ACE_M84",
			"ACE_M84"
		};
		respawnMagazines[]=
		{
			"rhsusf_8Rnd_Slug",
			"rhsusf_8Rnd_Slug",
			"rhsusf_8Rnd_Slug",
			"rhsusf_8Rnd_00Buck",
			"rhsusf_8Rnd_00Buck",
			"rhsusf_8Rnd_00Buck",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"ACE_M84",
			"ACE_M84",
			"ACE_M84"
		};
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_tourniquet",
			"ACE_CableTie",
			"ACE_DefusalKit",
			"MineDetector"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_tourniquet",
			"ACE_CableTie",
			"ACE_DefusalKit",
			"MineDetector"
		};
	};
	class I_LT_Marksman: I_LT_Infantry_Base
	{
		displayName="Marksman";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_SVD",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_SVD",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		respawnMagazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"rhs_10Rnd_762x54mmR_7N14",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
	};
	class I_LT_Sniper: I_LT_Base
	{
		displayName="Sniper";
		scope=2;
		scopeCurator=2;
		model="\A3\Characters_F_Mark\INDEP\i_fullghillie_f.p3d";
		uniformClass="U_LT_Ghillie";
		backpack="B_LT_AssaultPack";
		hiddenSelections[]=
		{
			"camo",
			"camo3",
			"camo4"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Mark\INDEP\Data\ghillie_coverall_aaf_co.paa",
			"\A3\Characters_F_Mark\Common\Data\ghillie_threads_sard_ca.paa",
			"\A3\Characters_F_Mark\Common\Data\ghillie_threads_5LOD_sard_co.paa"
		};
		weapons[]=
		{
			"W_LT_T5000",
			"rhs_weap_pp2000_folded",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_T5000",
			"rhs_weap_pp2000_folded",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20"
		};
		respawnMagazines[]=
		{
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_5Rnd_338lapua_t5000",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20"
		};
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"CUP_H_PMC_EP_Headset",
			"G_Balaclava_Flecktarn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"CUP_H_PMC_EP_Headset",
			"G_Balaclava_Flecktarn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Crewman: I_LT_Infantry_Base
	{
		displayName="Crewman";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Legstrap";
		engineer=1;
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Veh",
			"rhsusf_cvc_green_helmet",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Veh",
			"rhsusf_cvc_green_helmet",
			"rhsusf_oakley_goggles_clr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"rhs_weap_pp2000",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pp2000",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
		respawnMagazines[]=
		{
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag"
		};
	};
	class I_LT_Pilot: I_LT_Base
	{
		displayName="Pilot";
		scope=2;
		scopeCurator=2;
		model="\A3\characters_F\Common\pilot_f.p3d";
		uniformClass="U_LT_Pilot";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Data\pilot_suit_nato_co.paa"
		};
		backpack="B_LT_Legstrap";
		engineer=1;
		weapons[]=
		{
			"rhs_weap_pp2000",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_pp2000",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20"
		};
		respawnMagazines[]=
		{
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20",
			"rhs_mag_9x19mm_7n21_20"
		};
		linkedItems[]=
		{
			"RHS_jetpilot_usaf",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"RHS_jetpilot_usaf",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_HeliPilot: I_LT_Crewman
	{
		displayName="Helicopter Pilot";
		scope=2;
		scopeCurator=2;
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Veh",
			"H_PilotHelmetHeli_B",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Veh",
			"H_PilotHelmetHeli_B",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Hazmat_Base;
	class I_LT_Rifleman_H: I_LT_Hazmat_Base
	{
		displayName="Rifleman (HAZMAT)";
		scope=2;
		scopeCurator=2;
	};
	class I_LT_Scout_H: I_LT_Scout
	{
		displayName="Scout (HAZMAT)";
		scope=2;
		scopeCurator=2;
		editorSubcategory="LT_E_Chem";
		model="\a3\Characters_F_Enoch\Uniforms\Gorka_01_F.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_Enoch\Uniforms\Data\Gorka_01_Black_CO.paa"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_H_PMC_EP_Headset",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_H_PMC_EP_Headset",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Rifleman_GL_H: I_LT_Rifleman_GL
	{
		displayName="Grenadier (HAZMAT)";
		scope=2;
		scopeCurator=2;
		editorSubcategory="LT_E_Chem";
		model="\a3\Characters_F_Enoch\Uniforms\Gorka_01_F.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_Enoch\Uniforms\Data\Gorka_01_Black_CO.paa"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Grenadier",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Grenadier",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Autorifleman_H: I_LT_Autorifleman
	{
		displayName="Autorifleman (HAZMAT)";
		editorSubcategory="LT_E_Chem";
		model="\a3\Characters_F_Enoch\Uniforms\Gorka_01_F.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_Enoch\Uniforms\Data\Gorka_01_Black_CO.paa"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Empty",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Empty",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_GPMG_H: I_LT_GPMG
	{
		displayName="Machinegunner (HAZMAT)";
		editorSubcategory="LT_E_Chem";
		model="\a3\Characters_F_Enoch\Uniforms\Gorka_01_F.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_Enoch\Uniforms\Data\Gorka_01_Black_CO.paa"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Empty",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Empty",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_AT_H: I_LT_Hazmat_Base
	{
		displayName="Anti-Tank Specialist (HAZMAT)";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Carryall_AT";
		weapons[]=
		{
			"W_LT_VHSD2_Holo",
			"rhs_weap_rpg7",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_VHSD2_Holo",
			"rhs_weap_rpg7",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"rhs_rpg7_TBG7V_mag"
		};
		respawnMagazines[]=
		{
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"rhsgref_30rnd_556x45_vhs2_t",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"rhs_rpg7_TBG7V_mag"
		};
	};
	class I_LT_AA_H: I_LT_Hazmat_Base
	{
		displayName="Anti-Air Specialist (HAZMAT)";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_VHSD2_Holo",
			"hgun_ACPC2_F",
			"rhs_weap_fim92",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_VHSD2_Holo",
			"hgun_ACPC2_F",
			"rhs_weap_fim92",
			"Throw",
			"Put"
		};
	};
	class I_LT_Medic_H: I_LT_Medic
	{
		displayName="Medic (HAZMAT)";
		editorSubcategory="LT_E_Chem";
		model="\a3\Characters_F_Enoch\Uniforms\Gorka_01_F.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_Enoch\Uniforms\Data\Gorka_01_Black_CO.paa"
		};
		linkedItems[]=
		{
			"V_TacVestIR_blk",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVestIR_blk",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Engineer_H: I_LT_Engineer
	{
		displayName="Engineer (HAZMAT)";
		editorSubcategory="LT_E_Chem";
		model="\a3\Characters_F_Enoch\Uniforms\Gorka_01_F.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_Enoch\Uniforms\Data\Gorka_01_Black_CO.paa"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Marksman_H: I_LT_Marksman
	{
		displayName="Marksman (HAZMAT)";
		editorSubcategory="LT_E_Chem";
		model="\a3\Characters_F_Enoch\Uniforms\Gorka_01_F.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_Enoch\Uniforms\Data\Gorka_01_Black_CO.paa"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"rhsusf_opscore_bk_pelt",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_LT_Sniper_H: I_LT_Sniper
	{
		displayName="Sniper (HAZMAT)";
		editorSubcategory="LT_E_Chem";
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"CUP_H_PMC_EP_Headset",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"CUP_H_PMC_EP_Headset",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
};
class CfgMods
{
	author="johnyF";
};
