class CfgPatches
{
	class LT_SpecialForces_Units
	{
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"Liontooth_Base"
		};
		units[]=
		{
			"O_LT_SF_Rifleman",
			"O_LT_SF_Rifleman_GL",
			"O_LT_SF_Scout",
			"O_LT_SF_Medic",
			"O_LT_SF_Marksman",
			"O_LT_SF_Pathfinder",
			"O_LT_SF_Demoman",
			"O_LT_SF_Autorifleman",
			"O_LT_SF_GPMG",
			"O_LT_SF_AT",
			"O_LT_SF_AA",
			"I_LT_SF_Rifleman",
			"I_LT_SF_Rifleman_GL",
			"I_LT_SF_Scout",
			"I_LT_SF_Medic",
			"I_LT_SF_Marksman",
			"I_LT_SF_Pathfinder",
			"I_LT_SF_Demoman",
			"I_LT_SF_Autorifleman",
			"I_LT_SF_GPMG",
			"I_LT_SF_AT",
			"I_LT_SF_AA"
		};
	};
};