class CfgPatches
{
	class LT_SpecialForces_Units
	{
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"LiontoothGroup_Base"
		};
		units[]=
		{
			"U_LT_SF_Rifleman",
			"U_LT_SF_Rifleman_GL",
			"U_LT_SF_Scout",
			"U_LT_SF_Medic",
			"U_LT_SF_Marksman",
			"U_LT_SF_Pathfinder",
			"U_LT_SF_Demoman",
			"U_LT_SF_Autorifleman",
			"U_LT_SF_GPMG",
			"U_LT_SF_AT",
			"U_LT_SF_AA"
		};
	};
};
class CfgVehicles
{
	class U_LT_SpecialForces_Base;
	class U_LT_SF_Rifleman: U_LT_SpecialForces_Base
	{
		displayName="Recon Rifleman";
		scope=2;
		scopeCurator=2;
	};
	class U_LT_SF_Rifleman_GL: U_LT_SpecialForces_Base
	{
		displayName="Recon Rifleman (GL)";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_HK416_GL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_HK416_GL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class U_LT_SF_Scout: U_LT_SpecialForces_Base
	{
		displayName="Recon Scout";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_ASVAL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_ASVAL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		linkedItems[]=
		{
			"CUP_V_B_Ciras_Black2",
			"CUP_H_PMC_EP_Headset",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_Ciras_Black2",
			"CUP_H_PMC_EP_Headset",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class U_LT_SF_Medic: U_LT_SpecialForces_Base
	{
		displayName="Recon Medic";
		scope=2;
		scopeCurator=2;
		icon="iconManMedic";
		attendant=1;
		backpack="B_LT_MedicalPack";
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_morphine"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_morphine"
		};
		linkedItems[]=
		{
			"CUP_V_B_Ciras_Black",
			"CUP_H_OpsCore_Black",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_Ciras_Black",
			"CUP_H_OpsCore_Black",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class U_LT_SF_Marksman: U_LT_SpecialForces_Base
	{
		displayName="Recon Marksman";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_SCARH_DMR",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_SCARH_DMR",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class U_LT_SF_Pathfinder: U_LT_SpecialForces_Base
	{
		displayName="Recon Pathfinder";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_M107A1",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_M107A1",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class U_LT_SF_Demoman: U_LT_SpecialForces_Base
	{
		displayName="Demolitions Expert";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"rhs_weap_m32",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m32",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		linkedItems[]=
		{
			"CUP_V_PMC_IOTV_Black_Gren",
			"CUP_H_OpsCore_Black",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_IOTV_Black_Gren",
			"CUP_H_OpsCore_Black",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class U_LT_SF_Autorifleman: U_LT_SpecialForces_Base
	{
		displayName="Recon Autorifleman";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Carryall_Auto_SF";
		weapons[]=
		{
			"W_LT_M249_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_M249_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class U_LT_SF_GPMG: U_LT_SpecialForces_Base
	{
		displayName="Recon Machinegunner";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Carryall_GPMG_SF";
		weapons[]=
		{
			"W_LT_Negev_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_Negev_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"150Rnd_762x54_Box_Tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"150Rnd_762x54_Box_Tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class U_LT_SF_AT: U_LT_SpecialForces_Base
	{
		displayName="Recon Anti-Tank Specialist";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		backpack="B_LT_Carryall_AT";
		weapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_fim92",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_fim92",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_fim92_mag"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_fim92_mag"
		};
	};
	class U_LT_SF_AA: U_LT_SpecialForces_Base
	{
		displayName="Recon Anti-Air Specialist";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		weapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_smaw",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_smaw",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_smaw_HEDP"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_smaw_HEDP"
		};
	};
};
class CfgMods
{
	author="johnyF";
};
