#include "CfgPatches.hpp"

class CfgVehicles
{
	class LT_SpecialForces_Base;
	
	class O_LT_SF_Rifleman: LT_SpecialForces_Base
	{
		displayName="Recon Rifleman";
		scope=2;
		scopeCurator=2;
	};
	class O_LT_SF_Rifleman_GL: LT_SpecialForces_Base
	{
		displayName="Recon Rifleman (GL)";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_HK416_GL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_HK416_GL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class O_LT_SF_Scout: LT_SpecialForces_Base
	{
		displayName="Recon Scout";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_ASVAL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_ASVAL",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhs_20rnd_9x39mm_SP6",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		linkedItems[]=
		{
			"H_HeadSet_black_F",
			"G_Balaclava_TI_blk_F",
			"V_PlateCarrier1_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_HeadSet_black_F",
			"G_Balaclava_TI_blk_F",
			"V_PlateCarrier1_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_LT_SF_Medic: LT_SpecialForces_Base
	{
		displayName="Recon Medic";
		scope=2;
		scopeCurator=2;
		icon="iconManMedic";
		attendant=1;
		backpack="B_LT_MedicalPack";
		items[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_morphine"
		};
		respawnItems[]=
		{
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_adenosine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_morphine"
		};
		linkedItems[]=
		{
			"rhsusf_opscore_bk_pelt",
			"rhsusf_ANPVS_15",
			"rhs_googles_black",
			"V_TacVestIR_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"rhsusf_opscore_bk_pelt",
			"rhsusf_ANPVS_15",
			"rhs_googles_black",
			"V_TacVestIR_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_LT_SF_Marksman: LT_SpecialForces_Base
	{
		displayName="Recon Marksman";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_SCARH_DMR",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_SCARH_DMR",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class O_LT_SF_Pathfinder: LT_SpecialForces_Base
	{
		displayName="Recon Pathfinder";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"W_LT_M107A1",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_M107A1",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class O_LT_SF_Demoman: LT_SpecialForces_Base
	{
		displayName="Demolitions Expert";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"rhs_weap_m32",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m32",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		/*linkedItems[]=
		{
			"CUP_V_PMC_IOTV_Black_Gren",
			"rhsusf_opscore_bk_pelt",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_PMC_IOTV_Black_Gren",
			"rhsusf_opscore_bk_pelt",
			"CUP_RUS_Balaclava_blk",
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};*/
	};
	class O_LT_SF_Autorifleman: LT_SpecialForces_Base
	{
		displayName="Recon Autorifleman";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Carryall_Auto_SF";
		weapons[]=
		{
			"W_LT_M249_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_M249_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class O_LT_SF_GPMG: LT_SpecialForces_Base
	{
		displayName="Recon Machinegunner";
		scope=2;
		scopeCurator=2;
		backpack="B_LT_Carryall_GPMG_SF";
		weapons[]=
		{
			"W_LT_Negev_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_Negev_SF",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"150Rnd_762x54_Box_Tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
		respawnMagazines[]=
		{
			"150Rnd_762x54_Box_Tracer",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ"
		};
	};
	class O_LT_SF_AT: LT_SpecialForces_Base
	{
		displayName="Recon Anti-Tank Specialist";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		backpack="B_LT_Carryall_AT";
		weapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_rpg7",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_rpg7",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_rpg7_TBG7V_mag"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_rpg7_TBG7V_mag"
		};
	};
	class O_LT_SF_AA: LT_SpecialForces_Base
	{
		displayName="Recon Anti-Air Specialist";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		weapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_fim92",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"W_LT_HK416",
			"rhs_weap_fim92",
			"rhsusf_weap_glock17g4",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_fim92_mag"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_fim92_mag"
		};
	};

	class I_LT_SF_Rifleman: O_LT_SF_Rifleman
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_Rifleman_GL: O_LT_SF_Rifleman_GL
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_Scout: O_LT_SF_Scout
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_Medic: O_LT_SF_Medic
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_Marksman: O_LT_SF_Marksman
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_Pathfinder: O_LT_SF_Pathfinder
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_Demoman: O_LT_SF_Demoman
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_Autorifleman: O_LT_SF_Autorifleman
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_GPMG: O_LT_SF_GPMG
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_AT: O_LT_SF_AT
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
	class I_LT_SF_AA: O_LT_SF_AA
	{
		side=2;
		faction="LT_Group_I";
		uniformClass="U_I_LT_G3";
	};
};
class CfgMods
{
	author="johnyF";
};